name: stac_svg_example
description: An example demonstrating the use of stac_svg package.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  stac: ^1.3.1
  stac_core: ^1.3.0
  stac_svg:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
